Repository NOAA-GFDL/MOM6, pull requests merged in 2022-12, with the labels that each got.

#251 Use small minimum ustar in mixed layer restratification
  src/parameterizations/lateral/MOM_mixed_layer_restrat.F90
Labels: bug

#256 Document units in 8 lat_param or diag modules
  src/core/MOM_barotropic.F90
  src/diagnostics/MOM_sum_output.F90
  src/framework/MOM_write_cputime.F90
  src/framework/testing/MOM_file_parser_tests.F90
  src/parameterizations/lateral/MOM_MEKE_types.F90
  src/parameterizations/lateral/MOM_hor_visc.F90
  src/parameterizations/lateral/MOM_lateral_mixing_coeffs.F90
  src/tracer/MOM_tracer_flow_control.F90
Labels: documentation

#265 *Fix new scaling bug in ML restrat minimum ustar
  src/parameterizations/lateral/MOM_mixed_layer_restrat.F90
Labels: bug, answer-changing

#266 +Add runtime params KV_RESTRAT & RESTRAT_USTAR_MIN
  src/core/MOM.F90
  src/parameterizations/lateral/MOM_lateral_mixing_coeffs.F90
  src/parameterizations/lateral/MOM_mixed_layer_restrat.F90
Labels: enhancement, Parameter change

#272 (*)Correct two rescaling bugs in MOM_EOS
  src/core/MOM_checksum_packages.F90
  src/equation_of_state/MOM_EOS.F90
Labels: bug, documentation

#281 Reorder i- and j-loops to be stride-1 in memory
  src/diagnostics/MOM_spatial_means.F90
  src/initialization/MOM_shared_initialization.F90
  src/tracer/MOM_tracer_advect.F90
  src/user/Phillips_initialization.F90
  src/user/RGC_initialization.F90
  src/user/benchmark_initialization.F90
Labels: refactor

#268 Add GL90 parameterization for stacked shallow water
  src/core/MOM_dynamics_split_RK2.F90
  src/core/MOM_dynamics_unsplit.F90
  src/core/MOM_dynamics_unsplit_RK2.F90
  src/parameterizations/lateral/MOM_lateral_mixing_coeffs.F90
  src/parameterizations/vertical/MOM_vert_friction.F90
Labels: enhancement, Parameter change

#276 Rescale internal variables in reset_face_lengths_list
  src/core/MOM_porous_barriers.F90
  src/initialization/MOM_shared_initialization.F90
Labels: enhancement

#283 Avoid using the unscaled argument to MOM_get_param
  config_src/drivers/FMS_cap/MOM_surface_forcing_gfdl.F90
  config_src/drivers/solo_driver/MOM_surface_forcing.F90
  src/parameterizations/vertical/MOM_bulk_mixed_layer.F90
  src/parameterizations/vertical/MOM_vert_friction.F90
Labels: refactor

#289 +Add runtime parameters for MOM_wave_interface
  src/user/MOM_wave_interface.F90
Labels: documentation, Parameter change
