Repository NOAA-GFDL/MOM6, pull requests merged in 2022-11, with the labels that each got.

#232 *Fix bug with TIDAL_ENERGY_TYPE = "ER03"
  src/parameterizations/vertical/MOM_tidal_mixing.F90
Labels: bug, answer-changing

#236 Option to read horizontally varying KHTH from file
  src/parameterizations/lateral/MOM_thickness_diffuse.F90
Labels: enhancement

#238 +Correct reported units for 4 diagnostics
  src/core/MOM_CoriolisAdv.F90
  src/ice_shelf/MOM_ice_shelf.F90
  src/ice_shelf/MOM_ice_shelf_initialize.F90
  src/initialization/MOM_fixed_initialization.F90
  src/initialization/MOM_state_initialization.F90
  src/parameterizations/lateral/MOM_MEKE.F90
  src/tracer/MOM_neutral_diffusion.F90
  src/tracer/boundary_impulse_tracer.F90
Labels: bug, documentation

#239 (*)Rescale DENSE_WATER_EAST_SPONGE_SALT
  src/user/dense_water_initialization.F90
Labels: bug, answer-changing

#253 Document units in 9 vertical param modules
  src/parameterizations/vertical/MOM_bkgnd_mixing.F90
  src/parameterizations/vertical/MOM_bulk_mixed_layer.F90
  src/parameterizations/vertical/MOM_diabatic_aux.F90
  src/parameterizations/vertical/MOM_diabatic_driver.F90
  src/parameterizations/vertical/MOM_entrain_diffusive.F90
  src/parameterizations/vertical/MOM_kappa_shear.F90
  src/parameterizations/vertical/MOM_regularize_layers.F90
  src/parameterizations/vertical/MOM_set_diffusivity.F90
  src/parameterizations/vertical/MOM_set_viscosity.F90
Labels: documentation
