Repository NOAA-GFDL/MOM6, pull requests merged in 2022-03, with the labels that each got.

#78 +(*)Fix dimensional rescaling with HOMOGENIZE_FORCINGS
  src/core/MOM.F90
  src/core/MOM_forcing_type.F90
  src/diagnostics/MOM_spatial_means.F90
Labels: bug

#81 +Add Hybgen remapping options
  src/ALE/MOM_ALE.F90
  src/ALE/MOM_hybgen_remap.F90
  src/ALE/MOM_regridding.F90
  src/ALE/MOM_remapping.F90
  src/core/MOM_open_boundary.F90
  src/initialization/MOM_state_initialization.F90
  src/initialization/MOM_tracer_initialization_from_Z.F90
  src/ocean_data_assim/MOM_oda_incupd.F90
  src/parameterizations/vertical/MOM_ALE_sponge.F90
  src/parameterizations/vertical/MOM_CVMix_KPP.F90
Labels: enhancement

#83 +Add Laplacian diffusion of interface heights
  src/parameterizations/lateral/MOM_thickness_diffuse.F90
Labels: enhancement

#85 Avoid copying the tracer registry in advect_tracer
  src/tracer/MOM_tracer_advect.F90
Labels: enhancement

#86 (*)Fix rescaling in RGC_initialize_sponges
  src/user/RGC_initialization.F90
Labels: bug

#84 +(*)MOM_hor_visc bug fix and loop size cleanup
  src/parameterizations/lateral/MOM_hor_visc.F90
Labels: bug, enhancement, answer-changing

#87 +Stop logging NEW_SPONGES
  src/diagnostics/MOM_obsolete_params.F90
  src/initialization/MOM_state_initialization.F90
Labels: documentation

#80 Ice dynamics
  config_src/drivers/solo_driver/MOM_driver.F90
  src/core/MOM_forcing_type.F90
  src/ice_shelf/MOM_ice_shelf.F90
  src/ice_shelf/MOM_ice_shelf_dynamics.F90
  src/ice_shelf/MOM_ice_shelf_initialize.F90
Labels: enhancement

#88 fix bug in wave_speeds when openmp is on
  src/diagnostics/MOM_wave_speed.F90
Labels: bug, answer-changing

#89 +Gracefully handle longer input parameter lines
  src/framework/MOM_file_parser.F90
Labels: enhancement
