Repository NOAA-GFDL/MOM6, pull requests merged in 2022-04, with the labels that each got.

#103 Bugfix: remove pointer attribute from tides_CS in unsplit mode
  src/core/MOM_dynamics_unsplit.F90
  src/core/MOM_dynamics_unsplit_RK2.F90
Labels: bug

#106 Correct --with-driver args for coupled tests
  .testing/Makefile
Labels: bug

#107 +Document or eliminate undocumented interfaces
  config_src/drivers/mct_cap/mom_surface_forcing_mct.F90
  config_src/drivers/nuopc_cap/mom_surface_forcing_nuopc.F90
  config_src/infra/FMS1/MOM_domain_infra.F90
  config_src/infra/FMS1/MOM_interp_infra.F90
  config_src/infra/FMS2/MOM_domain_infra.F90
  config_src/infra/FMS2/MOM_interp_infra.F90
  src/framework/MOM_coupler_types.F90
  src/framework/MOM_diag_mediator.F90
  src/framework/MOM_domains.F90
  src/framework/MOM_horizontal_regridding.F90
  src/framework/MOM_interpolate.F90
  src/framework/MOM_io.F90
  src/parameterizations/lateral/MOM_thickness_diffuse.F90
  src/parameterizations/vertical/MOM_diabatic_driver.F90
Labels: documentation

#99 Add a deta_dt diagnostic to the split BT/BC mode
  src/core/MOM_dynamics_split_RK2.F90
Labels: enhancement

#117 +Fix some rescaling issues smoked out by the regional Bering domain
  src/ALE/MOM_ALE.F90
  src/core/MOM_barotropic.F90
  src/core/MOM_open_boundary.F90
  src/framework/MOM_horizontal_regridding.F90
  src/initialization/MOM_state_initialization.F90
  src/ocean_data_assim/MOM_oda_driver.F90
  src/parameterizations/vertical/MOM_ALE_sponge.F90
  src/parameterizations/vertical/MOM_energetic_PBL.F90
  src/parameterizations/vertical/MOM_tidal_mixing.F90
  src/parameterizations/vertical/MOM_vert_friction.F90
  src/tracer/MOM_lateral_boundary_diffusion.F90
  src/user/DOME_initialization.F90
  src/user/dyed_channel_initialization.F90
  src/user/dyed_obcs_initialization.F90
  src/user/supercritical_initialization.F90
  src/user/user_initialization.F90
Labels: bug, duplicate

#104 Fix some rescaling issues smoked out by the regional Bering domain
  src/ALE/MOM_ALE.F90
  src/core/MOM_barotropic.F90
  src/core/MOM_open_boundary.F90
  src/framework/MOM_horizontal_regridding.F90
  src/initialization/MOM_state_initialization.F90
  src/ocean_data_assim/MOM_oda_driver.F90
  src/parameterizations/vertical/MOM_ALE_sponge.F90
  src/parameterizations/vertical/MOM_energetic_PBL.F90
  src/parameterizations/vertical/MOM_tidal_mixing.F90
  src/parameterizations/vertical/MOM_vert_friction.F90
  src/tracer/MOM_lateral_boundary_diffusion.F90
  src/user/DOME_initialization.F90
  src/user/dyed_channel_initialization.F90
  src/user/dyed_obcs_initialization.F90
  src/user/supercritical_initialization.F90
  src/user/user_initialization.F90
Labels: bug
