Repository NOAA-GFDL/MOM6, pull requests merged in 2023-08, with the labels that each got.

#396 +(*)Minimum non-Boussinesq answer date of 20230701
  src/ALE/MOM_ALE.F90
  src/ALE/MOM_regridding.F90
  src/core/MOM.F90
  src/core/MOM_porous_barriers.F90
  src/diagnostics/MOM_diagnostics.F90
  src/framework/MOM_diag_mediator.F90
  src/initialization/MOM_state_initialization.F90
  src/initialization/MOM_tracer_initialization_from_Z.F90
  src/ocean_data_assim/MOM_oda_driver.F90
  src/parameterizations/lateral/MOM_hor_visc.F90
  src/parameterizations/lateral/MOM_lateral_mixing_coeffs.F90
  src/parameterizations/lateral/MOM_thickness_diffuse.F90
  src/parameterizations/vertical/MOM_ALE_sponge.F90
  src/parameterizations/vertical/MOM_energetic_PBL.F90
  src/parameterizations/vertical/MOM_opacity.F90
  src/parameterizations/vertical/MOM_regularize_layers.F90
  src/parameterizations/vertical/MOM_set_diffusivity.F90
  src/parameterizations/vertical/MOM_set_viscosity.F90
  src/parameterizations/vertical/MOM_tidal_mixing.F90
  src/parameterizations/vertical/MOM_vert_friction.F90
  src/tracer/MOM_neutral_diffusion.F90
  src/user/MOM_wave_interface.F90
Labels: answer-changing, Parameter change

#432 +Non-Boussinesq revisions to wave_interface
  src/core/MOM.F90
  src/core/MOM_dynamics_split_RK2.F90
  src/parameterizations/vertical/MOM_CVMix_KPP.F90
  src/parameterizations/vertical/MOM_energetic_PBL.F90
  src/user/MOM_wave_interface.F90
Labels: enhancement, answer-changing, Parameter change

#395 Ice shelf melt parameterization fixes
  src/ice_shelf/MOM_ice_shelf.F90
Labels: bug, answer-changing, Parameter change

#421 *Use tv%SpV_avg in non-Boussinesq regridding
  src/ALE/MOM_ALE.F90
  src/ALE/MOM_hybgen_unmix.F90
  src/ALE/MOM_regridding.F90
Labels: enhancement, answer-changing

#430 *Non-Boussinesq revision of diabatic_driver
  src/parameterizations/vertical/MOM_diabatic_driver.F90
Labels: enhancement, answer-changing

#422 +*Ignore SURFACE_ANSWER_DATE when non-Boussinesq
  src/core/MOM.F90
  src/core/MOM_interface_heights.F90
Labels: enhancement, answer-changing, Parameter change

#435 +*Non-Boussinesq revision of full_convection
  src/parameterizations/vertical/MOM_full_convection.F90
  src/parameterizations/vertical/MOM_set_diffusivity.F90
Labels: enhancement, answer-changing

#428 +*Non-Boussinesq revision of MOM_vertvisc.F90
  src/diagnostics/MOM_PointAccel.F90
  src/parameterizations/vertical/MOM_vert_friction.F90
Labels: enhancement, answer-changing

#445 *+Add forcing%tau_mag_gustless & tau_mag opt args
  src/core/MOM_forcing_type.F90
Labels: enhancement, answer-changing

#437 +*Non-Boussinesq revision of tidal_mixing and find_N2
  src/parameterizations/vertical/MOM_set_diffusivity.F90
  src/parameterizations/vertical/MOM_tidal_mixing.F90
Labels: enhancement, answer-changing, Parameter change

#452 *Fix allocate_forcing_by_ref tau_mag_gustless bug
  src/core/MOM_forcing_type.F90
Labels: bug

#438 Fix rescaling in regularize_surface debugging
  src/parameterizations/vertical/MOM_regularize_layers.F90
Labels: bug

#444 *Non-Boussinesq revision of 3 MOM_CVMix modules
  src/parameterizations/vertical/MOM_CVMix_conv.F90
  src/parameterizations/vertical/MOM_CVMix_ddiff.F90
  src/parameterizations/vertical/MOM_CVMix_shear.F90
Labels: enhancement, answer-changing

#446 *Non-Boussinesq revision of MOM_CVMix_KPP
  src/parameterizations/vertical/MOM_CVMix_KPP.F90
Labels: enhancement, answer-changing

#418 *Non-Boussinesq interface_filter
  src/parameterizations/lateral/MOM_interface_filter.F90
Labels: answer-changing

#440 *Non-Boussinesq revision of calc_isoneutral_slopes
  src/core/MOM_isopycnal_slopes.F90
Labels: enhancement, answer-changing

#442 Refactor rescaling of CFC_cap flux diagnostics
  src/tracer/MOM_CFC_cap.F90
Labels: refactor

#453 *Non-Boussinesq revision of set_diffusivity
  src/parameterizations/vertical/MOM_set_diffusivity.F90
Labels: enhancement, answer-changing

#439 *Non-Boussinesq refactoring of entrain_diffusive
  src/parameterizations/vertical/MOM_entrain_diffusive.F90
Labels: enhancement, answer-changing

#426 *+Non-Boussinesq form of mixedlayer_restrat
  src/parameterizations/lateral/MOM_mixed_layer_restrat.F90
Labels: bug, enhancement, answer-changing

#436 *Non-Boussinesq revision of kappa_shear
  src/parameterizations/vertical/MOM_kappa_shear.F90
Labels: enhancement, answer-changing

#441 +*Non-Boussinesq revision of MOM_sponge code
  src/parameterizations/vertical/MOM_sponge.F90
Labels: enhancement, answer-changing

#449 *Non-Boussinesq expressions for DOME inflow rates
  src/user/DOME_initialization.F90
Labels: enhancement, answer-changing

#458 *Non-Boussinesq revision of MOM.F90 for restarts
  src/core/MOM.F90
Labels: bug, enhancement, answer-changing

#461 +*Revise non-Boussinesq offline tracer diffusivity
  src/ALE/MOM_ALE.F90
  src/core/MOM.F90
  src/tracer/MOM_offline_aux.F90
  src/tracer/MOM_offline_main.F90
Labels: enhancement
