Repository NOAA-GFDL/MOM6, pull requests merged in 2024-04, with the labels that each got.

#581 Set flags properly for rotated tripolar grids
  config_src/infra/FMS1/MOM_domain_infra.F90
  config_src/infra/FMS2/MOM_domain_infra.F90
Labels: bug

#582 +Add get_netcdf_filename for a get_field_nc error
  src/framework/MOM_io_file.F90
  src/framework/MOM_netcdf.F90
Labels: documentation, enhancement

#585 +Rotationally symmetric epipycnal diffusion option
  src/tracer/MOM_tracer_hor_diff.F90
Labels: bug, enhancement

#592 Add units to the descriptions of 141 variables
  src/framework/MOM_diag_mediator.F90
  src/framework/MOM_diag_remap.F90
  src/framework/MOM_dyn_horgrid.F90
  src/framework/MOM_horizontal_regridding.F90
  src/framework/MOM_interpolate.F90
  src/framework/MOM_intrinsic_functions.F90
  src/framework/MOM_string_functions.F90
Labels: documentation

#586 Add units to the descriptions of 115 variables
  config_src/drivers/timing_tests/time_MOM_EOS.F90
  src/ALE/coord_adapt.F90
  src/ALE/regrid_interp.F90
  src/core/MOM_open_boundary.F90
  src/diagnostics/MOM_spatial_means.F90
  src/parameterizations/lateral/MOM_hor_visc.F90
  src/parameterizations/lateral/MOM_internal_tides.F90
  src/parameterizations/lateral/MOM_mixed_layer_restrat.F90
  src/parameterizations/stochastic/MOM_stochastics.F90
  src/parameterizations/vertical/MOM_vert_friction.F90
  src/tracer/ISOMIP_tracer.F90
  src/tracer/MOM_CFC_cap.F90
  src/tracer/MOM_OCMIP2_CFC.F90
  src/tracer/MOM_neutral_diffusion.F90
  src/tracer/MOM_offline_aux.F90
  src/tracer/MOM_offline_main.F90
  src/tracer/MOM_tracer_registry.F90
  src/tracer/MOM_tracer_types.F90
  src/tracer/boundary_impulse_tracer.F90
  src/tracer/dyed_obc_tracer.F90
  src/tracer/ideal_age_example.F90
  src/tracer/nw2_tracers.F90
  src/tracer/oil_tracer.F90
  src/tracer/pseudo_salt_tracer.F90
Labels: documentation

#593 (*)Fix Stokes drift spectrum rescaling
  src/user/MOM_wave_interface.F90
Labels: bug

#595 Fix for using tidal amplitude when determining the BBL thickness
  src/parameterizations/vertical/MOM_set_viscosity.F90
Labels: bug

#597 Better document variable units in 3 user modules
  src/user/Neverworld_initialization.F90
  src/user/basin_builder.F90
  src/user/tidal_bay_initialization.F90
Labels: documentation

#599 Cricital latitude modification of Henyey
  src/parameterizations/vertical/MOM_bkgnd_mixing.F90
Labels: enhancement, Parameter change

#601 Document units of 34 real variables in vertFPmix
  src/parameterizations/vertical/MOM_vert_friction.F90
Labels: documentation

#591 Refactoring density integrals for efficiency
  src/core/MOM_density_integrals.F90
Labels: refactor
