Repository NOAA-GFDL/MOM6, pull requests merged in 2024-08, with the labels that each got.

#693 Removes remap_via_sub_cells(), moving code into remapping_core_h()
  src/ALE/MOM_remapping.F90
Labels: refactor

#695 New diagnostic grids for comparing with WOA
  src/ALE/MOM_regridding.F90
Labels: enhancement

#711 * Fix for spatially varying Bodner fields.
  src/parameterizations/lateral/MOM_mixed_layer_restrat.F90
Labels: bug

#697 Fix USE_CONT_THICKNESS bug
  src/parameterizations/lateral/MOM_hor_visc.F90
Labels: bug, Parameter change

#703 Directional linear wave drag
  src/core/MOM_barotropic.F90
Labels: enhancement, Parameter change

#715 Restore computation of vorticity for ZB20
  src/parameterizations/lateral/MOM_hor_visc.F90
Labels: bug
