Repository NOAA-GFDL/MOM6, pull requests merged in 2024-09, with the labels that each got.

#716 *MOM-ocean/Main to NOAA-GFDL/main (2024-08-24) (Parentheses for FMA symmetry)
  config_src/drivers/FMS_cap/MOM_surface_forcing_gfdl.F90
  config_src/drivers/STALE_mct_cap/mom_surface_forcing_mct.F90
  config_src/drivers/nuopc_cap/mom_surface_forcing_nuopc.F90
  config_src/drivers/solo_driver/MOM_surface_forcing.F90
  config_src/drivers/solo_driver/user_surface_forcing.F90
  src/ALE/regrid_edge_values.F90
  src/core/MOM_CoriolisAdv.F90
  src/core/MOM_PressureForce_Montgomery.F90
  src/core/MOM_barotropic.F90
  src/core/MOM_continuity_PPM.F90
  src/core/MOM_density_integrals.F90
  src/core/MOM_forcing_type.F90
  src/core/MOM_grid.F90
  src/core/MOM_isopycnal_slopes.F90
  src/core/MOM_open_boundary.F90
  src/core/MOM_stoch_eos.F90
  src/core/MOM_transcribe_grid.F90
  src/diagnostics/MOM_diagnostics.F90
  src/diagnostics/MOM_sum_output.F90
  src/equation_of_state/MOM_EOS_Wright.F90
  src/equation_of_state/MOM_EOS_Wright_full.F90
  src/equation_of_state/MOM_EOS_Wright_red.F90
  src/equation_of_state/MOM_EOS_linear.F90
  src/framework/MOM_dyn_horgrid.F90
  src/ice_shelf/MOM_marine_ice.F90
  src/initialization/MOM_fixed_initialization.F90
  src/initialization/MOM_state_initialization.F90
  src/parameterizations/lateral/MOM_MEKE.F90
  src/parameterizations/lateral/MOM_Zanna_Bolton.F90
  src/parameterizations/lateral/MOM_hor_visc.F90
  src/parameterizations/lateral/MOM_interface_filter.F90
  src/parameterizations/lateral/MOM_internal_tides.F90
  src/parameterizations/lateral/MOM_lateral_mixing_coeffs.F90
  src/parameterizations/lateral/MOM_mixed_layer_restrat.F90
  src/parameterizations/lateral/MOM_thickness_diffuse.F90
  src/parameterizations/vertical/MOM_CVMix_KPP.F90
  src/parameterizations/vertical/MOM_CVMix_shear.F90
  src/parameterizations/vertical/MOM_bulk_mixed_layer.F90
  src/parameterizations/vertical/MOM_diabatic_aux.F90
  src/parameterizations/vertical/MOM_energetic_PBL.F90
  src/parameterizations/vertical/MOM_kappa_shear.F90
  src/parameterizations/vertical/MOM_set_diffusivity.F90
  src/parameterizations/vertical/MOM_set_viscosity.F90
  src/parameterizations/vertical/MOM_vert_friction.F90
  src/tracer/MOM_tracer_advect.F90
  src/tracer/MOM_tracer_hor_diff.F90
  src/tracer/advection_test_tracer.F90
  src/user/Idealized_Hurricane.F90
  src/user/MOM_wave_interface.F90
  src/user/Neverworld_initialization.F90
  src/user/SCM_CVMix_tests.F90
  src/user/basin_builder.F90
  src/user/circle_obcs_initialization.F90
  src/user/seamount_initialization.F90
Labels: enhancement, answer-changing

#675 Streaming filter
  src/core/MOM_barotropic.F90
  src/parameterizations/lateral/MOM_streaming_filter.F90
Labels: enhancement, Parameter change

#712 Rotate ice shelf forcing and initialization
  src/core/MOM.F90
  src/ice_shelf/MOM_ice_shelf.F90
Labels: enhancement

#724 Change the default of VISC_REM_CONT_HVEL_FIX
  src/core/MOM_continuity_PPM.F90
Labels: bug, Parameter change
