Repository NOAA-GFDL/MOM6, pull requests merged in 2024-12, with the labels that each got.

#762 Remove extra copy of compute_global_grid_integrals
  src/initialization/MOM_shared_initialization.F90
  src/initialization/MOM_state_initialization.F90
Labels: refactor

#741 Refactor of vertical reconstruction adding six new schemes
  .testing/Makefile
  config_src/drivers/timing_tests/time_MOM_remapping.F90
  config_src/drivers/unit_tests/test_MOM_remapping.F90
  config_src/drivers/unit_tests/test_numerical_testing_type.F90
  docs/discrete_space.rst
  docs/zotero.bib
  src/ALE/MOM_ALE.F90
  src/ALE/MOM_remapping.F90
  src/ALE/Recon1d_EMPLM_CWK.F90
  src/ALE/Recon1d_EMPLM_WA.F90
  src/ALE/Recon1d_EMPLM_WA_poly.F90
  src/ALE/Recon1d_EPPM_CWK.F90
  src/ALE/Recon1d_MPLM_CWK.F90
  src/ALE/Recon1d_MPLM_WA.F90
  src/ALE/Recon1d_MPLM_WA_poly.F90
  src/ALE/Recon1d_PCM.F90
  src/ALE/Recon1d_PLM_CW.F90
  src/ALE/Recon1d_PLM_CWK.F90
  src/ALE/Recon1d_PLM_hybgen.F90
  src/ALE/Recon1d_PPM_CW.F90
  src/ALE/Recon1d_PPM_CWK.F90
  src/ALE/Recon1d_PPM_H4_2018.F90
  src/ALE/Recon1d_PPM_H4_2019.F90
  src/ALE/Recon1d_PPM_hybgen.F90
  src/ALE/Recon1d_type.F90
  src/ALE/_Vertical_Reconstruction.dox
  src/ALE/remapping_attic.F90
  src/framework/numerical_testing_type.F90
Labels: documentation, enhancement, refactor

#770 +*Obsolete WIND_CONFIG = "SCM_ideal_hurr"
  config_src/drivers/solo_driver/MOM_surface_forcing.F90
  src/user/Idealized_Hurricane.F90
Labels: Parameter change

#783 Bug fixes for sea surface height related diagnostics/checks
  src/core/MOM.F90
Labels: bug

#784 Update MOM_wave_interface.F90
  src/user/MOM_wave_interface.F90
Labels: bug
