Repository NOAA-GFDL/MOM6, pull requests merged in 2024-06, with the labels that each got.

#617 Spatially variable fields for MLE%Bodner
  src/parameterizations/lateral/MOM_mixed_layer_restrat.F90
Labels: enhancement, Parameter change

#611 +(*)Refactor Idealize_Hurricane
  src/user/Idealized_Hurricane.F90
Labels: bug, documentation, enhancement, answer-changing

#643 Add rescaling parameter to kappa shear
  src/parameterizations/vertical/MOM_kappa_shear.F90
Labels: enhancement, Parameter change

#659 +Add ROBUST_STOKES_PGF and LA_MISALIGNMENT_BUG
  src/user/MOM_wave_interface.F90
Labels: bug, enhancement

#613 Add units to the descriptions of 79 variables
  config_src/drivers/ice_solo_driver/atmos_ocean_fluxes.F90
  config_src/drivers/ice_solo_driver/ice_shelf_driver.F90
  config_src/drivers/solo_driver/atmos_ocean_fluxes.F90
  src/core/MOM_variables.F90
  src/framework/MOM_coms.F90
  src/framework/MOM_coupler_types.F90
  src/framework/MOM_intrinsic_functions.F90
  src/framework/MOM_random.F90
  src/ocean_data_assim/MOM_oda_driver.F90
  src/ocean_data_assim/MOM_oda_incupd.F90
  src/parameterizations/lateral/MOM_MEKE.F90
  src/user/RGC_initialization.F90
Labels: documentation

#633 +(*)Fix sign of neutral_slope_x diagnostic with no EOS
  src/core/MOM_isopycnal_slopes.F90
  src/parameterizations/lateral/MOM_lateral_mixing_coeffs.F90
  src/parameterizations/lateral/MOM_thickness_diffuse.F90
Labels: bug, answer-changing

#654 +Add DETERMINE_TEMP_CONVERGENCE_BUG parameter
  src/tracer/MOM_tracer_Z_init.F90
Labels: bug, Parameter change

#635 (*)Fix Kd_interface diagnostic in newer diabatic_ALE
  src/parameterizations/vertical/MOM_diabatic_driver.F90
Labels: bug

#638 +(*)Fix rotation of coupler_type variables
  src/core/MOM.F90
  src/core/MOM_forcing_type.F90
  src/core/MOM_variables.F90
  src/framework/MOM_coupler_types.F90
  src/ice_shelf/MOM_ice_shelf.F90
  src/tracer/DOME_tracer.F90
  src/tracer/ISOMIP_tracer.F90
  src/tracer/MOM_OCMIP2_CFC.F90
  src/tracer/advection_test_tracer.F90
  src/tracer/boundary_impulse_tracer.F90
  src/tracer/dye_example.F90
  src/tracer/ideal_age_example.F90
  src/tracer/oil_tracer.F90
  src/tracer/tracer_example.F90
Labels: bug

#629 Refactor PressureForce_FV before ice shelf fixes
  src/core/MOM_PressureForce_FV.F90
Labels: refactor

#636 (*)Avoid diagnostic seg fault in a 10km deep ocean
  src/ALE/MOM_regridding.F90
Labels: bug

#656 +Add BACKSCATTER_UNDERBOUND
  src/parameterizations/lateral/MOM_hor_visc.F90
Labels: enhancement, Parameter change
