Repository NOAA-GFDL/MOM6, pull requests merged in 2024-05, with the labels that each got.

#608 Add INIT_BOUNDARY_EXTRAP parameter and function to allow ALE boundary extrapolation behaviour to differ at initialisation and in model run
  src/ALE/MOM_ALE.F90
  src/core/MOM.F90
Labels: enhancement, Parameter change

#606 +Rotationally symmetric KPP_smooth_BLD option
  src/parameterizations/vertical/MOM_CVMix_KPP.F90
Labels: Parameter change

#620 +Fix multiple bugs when MEKE_GM_SRC_ALT is True
  src/parameterizations/lateral/MOM_thickness_diffuse.F90
Labels: bug, Parameter change

#618 Added missing values for vector u2_bg(:) within set_viscous_ML
  src/parameterizations/vertical/MOM_set_viscosity.F90
Labels: bug

#604 +(*)Fix USE_QG_LEITH_VISC = True reproducibility
  src/core/MOM.F90
  src/core/MOM_dynamics_split_RK2.F90
  src/core/MOM_dynamics_split_RK2b.F90
  src/core/MOM_dynamics_unsplit.F90
  src/core/MOM_dynamics_unsplit_RK2.F90
  src/parameterizations/lateral/MOM_hor_visc.F90
  src/parameterizations/lateral/MOM_lateral_mixing_coeffs.F90
Labels: bug, enhancement

#624 Fix error in diagnostic axis registration for grid space axes
  src/diagnostics/MOM_obsolete_params.F90
  src/framework/MOM_diag_mediator.F90
Labels: bug

#602 Better variables for updated masks in fill_miss_2d
  src/framework/MOM_horizontal_regridding.F90
Labels: documentation, refactor

#650 *Fix ALE_remap_scalar call with h_in_Z_units
  src/initialization/MOM_tracer_initialization_from_Z.F90
Labels: bug

#612 (*)Refactor and document soliton_initialization
  src/initialization/MOM_state_initialization.F90
  src/user/soliton_initialization.F90
Labels: documentation, refactor, answer-changing

#651 Fix TEOS10 argument descriptions
  src/equation_of_state/MOM_EOS_TEOS10.F90
Labels: documentation
