Repository NOAA-GFDL/MOM6, pull requests merged in 2025-02, with the labels that each got.

#804 +Add PHILLIPS_ANSWER_DATE runtime parameter
  src/user/Phillips_initialization.F90
Labels: enhancement, Parameter change

#828 Describe the units of 33 real function results
  src/core/MOM_open_boundary.F90
  src/parameterizations/lateral/MOM_MEKE.F90
  src/tracer/MOM_hor_bnd_diffusion.F90
  src/tracer/MOM_neutral_diffusion.F90
  src/tracer/nw2_tracers.F90
  src/user/MOM_wave_interface.F90
  src/user/Neverworld_initialization.F90
  src/user/basin_builder.F90
Labels: documentation

#831 +Obsoleted INTERNAL_TIDE_CORNER_ADVECT
  src/diagnostics/MOM_obsolete_params.F90
  src/parameterizations/lateral/MOM_internal_tides.F90
Labels: documentation, Parameter change

#829 +Find fluxes%netFWGlobalAdj in rescaled units
  config_src/drivers/FMS_cap/MOM_surface_forcing_gfdl.F90
  config_src/drivers/STALE_mct_cap/mom_surface_forcing_mct.F90
  config_src/drivers/nuopc_cap/mom_surface_forcing_nuopc.F90
  src/core/MOM_forcing_type.F90
Labels: refactor

#830 Dimensional rescaling in MOM_state_stats
  src/core/MOM_checksum_packages.F90
Labels: refactor

#815 Frequency-dependent internal wave drag
  src/core/MOM_barotropic.F90
  src/parameterizations/lateral/MOM_streaming_filter.F90
  src/parameterizations/lateral/MOM_wave_drag.F90
Labels: enhancement

#818 Passing shelf_sfc_mass_flux to ice shelf
  config_src/drivers/FMS_cap/MOM_surface_forcing_gfdl.F90
  src/ice_shelf/MOM_ice_shelf.F90
Labels: enhancement
