Repository NOAA-GFDL/MOM6, pull requests merged in 2025-07, with the labels that each got.

#927 Avoid setting 3d OBC arrays in unrotated OBC type
  src/core/MOM.F90
  src/core/MOM_open_boundary.F90
Labels: refactor

#920 +Add the new parameter INTERPOLATED_SQG_STRUCTURE
  src/parameterizations/lateral/MOM_lateral_mixing_coeffs.F90
Labels: enhancement, Parameter change

#921 Convert 28 static arrays into dynamic arrays
  src/core/MOM_barotropic.F90
  src/parameterizations/lateral/MOM_hor_visc.F90
  src/parameterizations/stochastic/MOM_stochastics.F90
Labels: refactor

#932 Add conditional halo pass for frazil inside make_frazil
  src/core/MOM.F90
  src/core/MOM_variables.F90
  src/parameterizations/vertical/MOM_diabatic_aux.F90
Labels: bug

#933 +Do not call write_ocean_geometry_file from MOM_initialize_fixed
  config_src/drivers/ice_solo_driver/ice_shelf_driver.F90
  src/core/MOM.F90
  src/initialization/MOM_fixed_initialization.F90
  src/ocean_data_assim/MOM_oda_driver.F90
Labels: refactor

#939 (*)Fix bugs in rotate_OBC_segment_data
  src/core/MOM_open_boundary.F90
Labels: bug, answer-changing
