Repository NOAA-GFDL/MOM6, pull requests merged in 2025-05, with the labels that each got.

#891 +Refactor shelfwave OBC code
  src/user/shelfwave_initialization.F90
Labels: bug, Parameter change

#887 Diagnose more integrated fluxes in rescaled units
  src/core/MOM_forcing_type.F90
Labels: refactor

#894 Correct variable units in comments in 4 modules
  src/core/MOM_forcing_type.F90
  src/core/MOM_grid.F90
  src/user/RGC_initialization.F90
  src/user/dumbbell_initialization.F90
Labels: refactor

#889 Replace checksum scale arguments with unscale
  src/diagnostics/MOM_debugging.F90
  src/tracer/MARBL_tracers.F90
  src/tracer/MOM_hor_bnd_diffusion.F90
Labels: refactor

#883 Add compressibility to linear equation of state
  src/equation_of_state/MOM_EOS.F90
  src/equation_of_state/MOM_EOS_linear.F90
Labels: enhancement, Parameter change

#897 +Add optional logunit argument to chksum()
  src/framework/MOM_checksums.F90
Labels: enhancement

#898 +Add SSH_u_OBC and ubt_OBC diagnostics
  src/core/MOM_barotropic.F90
Labels: enhancement

#899 Glob unit tests
  .github/workflows/verify-linux.yml
Labels: enhancement

#901 *Fix PE-count dependency with some kinds of OBCs
  src/core/MOM.F90
  src/core/MOM_open_boundary.F90
  src/initialization/MOM_state_initialization.F90
Labels: bug, answer-changing

#904 +OBC grid rotation debugging code
  src/core/MOM.F90
  src/core/MOM_boundary_update.F90
  src/core/MOM_dynamics_split_RK2.F90
  src/core/MOM_dynamics_split_RK2b.F90
  src/core/MOM_open_boundary.F90
  src/initialization/MOM_state_initialization.F90
Labels: enhancement, Parameter change

#902 Consolidate reproducible sum with unit tests
  .testing/tools/disp_timing.py
  config_src/drivers/timing_tests/time_reproducing_sum.F90
  config_src/drivers/unit_drivers/MOM_sum_driver.F90
  config_src/drivers/unit_tests/test_reproducing_sum.F90
  config_src/infra/FMS1/MOM_domain_infra.F90
  config_src/infra/FMS2/MOM_domain_infra.F90
  src/framework/MOM_coms.F90
  src/framework/MOM_domains.F90
Labels: bug, enhancement, refactor

#840 (*)Consolidate conversion of 4 salt tendency diags
  src/parameterizations/vertical/MOM_diabatic_driver.F90
Labels: refactor, answer-changing

#906 make clipping of diffusivities to Kd_max more consistent
  src/parameterizations/lateral/MOM_internal_tides.F90
  src/parameterizations/vertical/MOM_set_diffusivity.F90
Labels: answer-changing

#905 +(*)Correct OBC indexing bugs and errors with OBC grid rotation
  src/core/MOM_open_boundary.F90
Labels: bug, enhancement, answer-changing, Parameter change
