Repository NOAA-GFDL/MOM6, pull requests merged in 2025-06, with the labels that each got.

#912 Rewrite vertvisc() and vertvisc_remnant() loops to kji form
  src/parameterizations/vertical/MOM_vert_friction.F90
Labels: enhancement, refactor

#909 +(*)Fix bugs with dyed_channel_update_flow
  src/core/MOM_boundary_update.F90
  src/user/dyed_channel_initialization.F90
Labels: bug, enhancement, answer-changing, Parameter change

#908 (*)tidal_bay_set_OBC_data works with grid rotation
  src/user/tidal_bay_initialization.F90
Labels: bug, enhancement, answer-changing

#918 +Add the runtime parameter ENABLE_BUGS_BY_DEFAULT
  src/core/MOM.F90
  src/core/MOM_PressureForce_FV.F90
  src/core/MOM_barotropic.F90
  src/core/MOM_dynamics_split_RK2.F90
  src/core/MOM_dynamics_split_RK2b.F90
  src/core/MOM_open_boundary.F90
  src/initialization/MOM_state_initialization.F90
  src/parameterizations/lateral/MOM_hor_visc.F90
  src/parameterizations/lateral/MOM_lateral_mixing_coeffs.F90
  src/parameterizations/lateral/MOM_thickness_diffuse.F90
  src/parameterizations/vertical/MOM_energetic_PBL.F90
  src/parameterizations/vertical/MOM_kappa_shear.F90
  src/tracer/MOM_tracer_Z_init.F90
  src/tracer/MOM_tracer_hor_diff.F90
  src/user/Idealized_Hurricane.F90
  src/user/MOM_wave_interface.F90
  src/user/dyed_channel_initialization.F90
Labels: Parameter change

#916 *Fix PE-layout reproducibility with interior OBCs
  src/core/MOM_barotropic.F90
Labels: bug, answer-changing, Parameter change
