Repository NOAA-GFDL/MOM6, pull requests merged in 2025-03, with the labels that each got.

#761 Move Regridding and Remapping Out of step_MOM_thermo
  src/core/MOM.F90
Labels: refactor

#844 Update btstep negative eta warning
  src/core/MOM_barotropic.F90
Labels: documentation

#839 +Steps to correct Kelvin_initialization issues
  src/user/Kelvin_initialization.F90
Labels: documentation

#846 Updates MOM_kappa_shear averaging and diagnostics.
  src/parameterizations/vertical/MOM_kappa_shear.F90
Labels: enhancement, Parameter change

#849 *Improvements to internal Kelvin wave
  src/user/Kelvin_initialization.F90
Labels: bug, answer-changing

#850 Add INTERFACE_FILTER_DT_BUG
  src/core/MOM.F90
Labels: bug, Parameter change

#845 Move some parts of btstep() into subroutines
  src/core/MOM_barotropic.F90
Labels: refactor

#862 Horvisc: Reorder if-blocks in rescaled Kh
  src/parameterizations/lateral/MOM_hor_visc.F90
Labels: refactor

#864 Add variable dimensions to available_diags file
  src/framework/MOM_diag_mediator.F90
Labels: enhancement
