Repository NOAA-GFDL/MOM6, pull requests merged in 2025-09, with the labels that each got.

#946 Added the WENO schemes to reconstruct PV in MOM_CoriolisAdv
  src/core/MOM_CoriolisAdv.F90
  src/core/MOM_dynamics_split_RK2.F90
  src/core/MOM_dynamics_split_RK2b.F90
  src/core/MOM_dynamics_unsplit.F90
  src/core/MOM_dynamics_unsplit_RK2.F90
Labels: enhancement, Parameter change

#962 +Add RESCALE_STRONG_DRAG
  src/core/MOM_barotropic.F90
Labels: bug, enhancement, Parameter change

#969 +Correct halo update sizes and reduce halo updates
  src/core/MOM.F90
  src/core/MOM_dynamics_split_RK2.F90
  src/core/MOM_dynamics_split_RK2b.F90
  src/core/MOM_dynamics_unsplit.F90
  src/core/MOM_dynamics_unsplit_RK2.F90
Labels: refactor

#964 Bug fix in MOM_open_boundary
  src/core/MOM_open_boundary.F90
Labels: bug, answer-changing
