Repository NOAA-GFDL/MOM6, pull requests merged in 2025-01, with the labels that each got.

#789 Updates to use EPBL_BBL_EFFIC
  src/parameterizations/vertical/MOM_energetic_PBL.F90
  src/parameterizations/vertical/MOM_set_diffusivity.F90
Labels: bug, answer-changing

#792 Corrected the rescaling of 5 KPP diagnostics
  src/parameterizations/vertical/MOM_CVMix_KPP.F90
  src/tracer/MOM_tracer_registry.F90
Labels: bug

#797 Forget to set descale in reproducing_sum_3d
  src/framework/MOM_coms.F90
Labels: bug

#788 Fix ALE_sponge tendency diagnostic units
  src/parameterizations/vertical/MOM_ALE_sponge.F90
Labels: documentation

#776 Refactor horizontally_average_field
  src/framework/MOM_diag_remap.F90
Labels: refactor

#777 +Refactor homogenize_field and revise its interface
  src/framework/MOM_horizontal_regridding.F90
  src/initialization/MOM_state_initialization.F90
Labels: refactor

#795 Refactor ice shelf rescaling and diagnostic calcs
  src/ice_shelf/MOM_ice_shelf.F90
  src/ice_shelf/MOM_ice_shelf_dynamics.F90
  src/ice_shelf/MOM_ice_shelf_initialize.F90
Labels: bug, refactor

#793 Users set solo driver forcing time records per day
  config_src/drivers/solo_driver/MOM_surface_forcing.F90
Labels: bug, enhancement

#775 +Refactor MOM_opacity to replace hard-coded params
  src/parameterizations/vertical/MOM_opacity.F90
Labels: Parameter change

#800 Add ice shelf pressure initialisation bug fix
  src/core/MOM_density_integrals.F90
  src/initialization/MOM_state_initialization.F90
Labels: bug

#796 +Add the optional argument old_name to get_param()
  src/diagnostics/MOM_obsolete_params.F90
  src/framework/MOM_file_parser.F90
Labels: enhancement

#766 +Add grid_unit_to_L to the ocean_grid_type
  src/core/MOM_grid.F90
  src/core/MOM_transcribe_grid.F90
  src/framework/MOM_dyn_horgrid.F90
  src/ice_shelf/MOM_ice_shelf_diag_mediator.F90
  src/initialization/MOM_grid_initialize.F90
  src/initialization/MOM_shared_initialization.F90
  src/initialization/MOM_state_initialization.F90
  src/user/DOME_initialization.F90
  src/user/ISOMIP_initialization.F90
  src/user/Idealized_Hurricane.F90
  src/user/Kelvin_initialization.F90
  src/user/Rossby_front_2d_initialization.F90
  src/user/soliton_initialization.F90
Labels: enhancement

#769 +Remove dyn_horgrid_type%Rad_Earth and ocean_grid_type%Rad_Earth
  src/core/MOM_grid.F90
  src/core/MOM_transcribe_grid.F90
  src/framework/MOM_dyn_horgrid.F90
  src/initialization/MOM_grid_initialize.F90
Labels: refactor

#725 Nodal modulation
  src/core/MOM_open_boundary.F90
  src/diagnostics/MOM_harmonic_analysis.F90
  src/parameterizations/lateral/MOM_tidal_forcing.F90
Labels: bug, enhancement, Parameter change

#779 Correct unit conversion for BS_coeff_h and BS_coeff_q diagnostics
  src/parameterizations/lateral/MOM_hor_visc.F90
Labels: bug

#763 Fix rescaling of internal tide debugging code
  src/parameterizations/lateral/MOM_MEKE.F90
  src/parameterizations/lateral/MOM_internal_tides.F90
  src/parameterizations/vertical/MOM_set_diffusivity.F90
Labels: documentation, refactor

#807 Refactor spherical_harmonics_forward
  src/parameterizations/lateral/MOM_spherical_harmonics.F90
Labels: refactor

#805 Rescale 6 ice shelf variables
  src/ice_shelf/MOM_ice_shelf_dynamics.F90
  src/ice_shelf/MOM_ice_shelf_initialize.F90
Labels: refactor

#757 Add Option to Specify Tracer Advection Time Step
  src/core/MOM.F90
Labels: enhancement, Parameter change
